cpufreq: fix compile error with percpu cpu_init_done
Since we don't actually need cpufreq.h in mpdecision, just c&p
the sysfs stuff we need.

In file included from arch/arm/mach-msm/msm_mpdecision.c:28:0:
include/linux/cpufreq.h:174:28: error: unknown type name 'cpufreq_init_done'

Signed-off-by: Dennis Rassmann <showp1984@gmail.com>